version: '3'
services:
  db:
#      image: 'postgres:16-alpine'
#      container_name: db
#      environment:
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=postgres
#        - POSTGRES_DB=ems
      image: mysql:latest
      container_name: mysqldb
      environment:
        MYSQL_ROOT_PASSWORD: Abc@123456
        MYSQL_DATABASE: sep

      volumes:
        - ./initdata:/docker-entrypoint-initdb.d/
  app:
    image: 'dongho01/sep-java-springboot-docker:v1.1.1'
    build:
      context: .
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/sep
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Abc@123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:2000
#  frontend:
#    image: 'dongho01/sep-fe-docker:v1.0.0'
#    container_name: frontend
#    ports:
#      - 8090:80


