version: '3'
services:
  mysqldb:
#      image: 'postgres:16-alpine'
#      container_name: db
#      environment:
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=postgres
#        - POSTGRES_DB=ems
      image: mysql:8.0.32
      hostname: "mysqldb"
      container_name: mysqldb
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: sep
      networks:
        - spring-mysql
      ports:
        - 3306:3306
      volumes:
        - ./initdata:/docker-entrypoint-initdb.d/
#  maildev:
#    image: maildev/maildev
#    restart: always
#    ports:
#      - "587:587"
  app:
    image: 'phundhe151425/sep-be:latest'
#    image: 'sep-be'
    container_name: app
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/sep?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_USERNAME=hophuongdong25052001@gmail.com
      - SPRING_MAIL_PASSWORD=efxx uzga abuy kpyc
      - SPRING_MAIL_PORT=587
    networks:
      - spring-mysql
    ports:
      - 2000:8080

  frontend:
#    image: 'sep-fe'
    image: 'phundhe151425/sep-fe:latest'
    container_name: frontend
    ports:
      - 2001:80
    networks:
      - spring-mysql
networks:
  spring-mysql:

