version: '3'
services:
#  db:
#      image: 'postgres:16-alpine'
#      container_name: db
#      environment:
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=postgres
#        - POSTGRES_DB=ems
#      volumes:
#        - ./initdata:/docker-entrypoint-initdb.d/
  app:
    image: 'dongho01/sep-java-springboot-docker:v1.1.1'
    build:
      context: .
    container_name: app
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ems
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:2000
  frontend:
    image: 'dongho01/sep-fe-docker:v1.0.0'
    container_name: frontend
    ports:
      - 8090:80


